export interface StudentReadiness {
  id: string;
  name: string;
  avatar: string;
  email: string;
  grade: string;
  readiness: number;
  growth: number;
  academicScore: number;
  careerScore: number;
  socialScore: number;
  status: 'on-track' | 'at-risk' | 'needs-attention';
}

export const studentReadinessData: StudentReadiness[] = [
  {
    id: 'STD001',
    name: 'Alice Smith',
    avatar: '/images/avatar/1.png',
    email: 'alice.smith@school.edu',
    grade: 'Grade 8',
    readiness: 83,
    growth: 5,
    academicScore: 85,
    careerScore: 80,
    socialScore: 82,
    status: 'on-track',
  },
  {
    id: 'STD002',
    name: 'John Doe',
    avatar: '/images/avatar/2.png',
    email: 'john.doe@school.edu',
    grade: 'Grade 8',
    readiness: 61,
    growth: -2,
    academicScore: 55,
    careerScore: 65,
    socialScore: 70,
    status: 'at-risk',
  },
  {
    id: 'STD003',
    name: 'Rano K.',
    avatar: '/images/avatar/3.png',
    email: 'rano.k@school.edu',
    grade: 'Grade 8',
    readiness: 74,
    growth: 8,
    academicScore: 70,
    careerScore: 80,
    socialScore: 75,
    status: 'on-track',
  },
  {
    id: 'STD004',
    name: 'Maria Garcia',
    avatar: '/images/avatar/4.png',
    email: 'maria.garcia@school.edu',
    grade: 'Grade 9',
    readiness: 78,
    growth: 3,
    academicScore: 85,
    careerScore: 75,
    socialScore: 70,
    status: 'on-track',
  },
  {
    id: 'STD005',
    name: 'Robert Johnson',
    avatar: '/images/avatar/5.png',
    email: 'robert.j@school.edu',
    grade: 'Grade 9',
    readiness: 65,
    growth: 0,
    academicScore: 60,
    careerScore: 70,
    socialScore: 65,
    status: 'needs-attention',
  },
  {
    id: 'STD006',
    name: 'Emily Brown',
    avatar: '/images/avatar/6.png',
    email: 'emily.b@school.edu',
    grade: 'Grade 9',
    readiness: 90,
    growth: 7,
    academicScore: 95,
    careerScore: 85,
    socialScore: 90,
    status: 'on-track',
  },
  {
    id: 'STD007',
    name: 'Michael Lee',
    avatar: '/images/avatar/7.png',
    email: 'michael.l@school.edu',
    grade: 'Grade 10',
    readiness: 71,
    growth: 4,
    academicScore: 75,
    careerScore: 70,
    socialScore: 65,
    status: 'on-track',
  },
  {
    id: 'STD008',
    name: 'Sarah Wilson',
    avatar: '/images/avatar/8.png',
    email: 'sarah.w@school.edu',
    grade: 'Grade 10',
    readiness: 58,
    growth: -3,
    academicScore: 55,
    careerScore: 60,
    socialScore: 60,
    status: 'at-risk',
  },
  {
    id: 'STD009',
    name: 'David Martinez',
    avatar: '/images/avatar/9.png',
    email: 'david.m@school.edu',
    grade: 'Grade 10',
    readiness: 85,
    growth: 6,
    academicScore: 80,
    careerScore: 90,
    socialScore: 85,
    status: 'on-track',
  },
  {
    id: 'STD010',
    name: 'Jessica Taylor',
    avatar: '/images/avatar/10.png',
    email: 'jessica.t@school.edu',
    grade: 'Grade 10',
    readiness: 76,
    growth: 2,
    academicScore: 75,
    careerScore: 75,
    socialScore: 80,
    status: 'on-track',
  },
];
